from .case_exceptions import CaseError